name: emd_flutter_identity
description: Auth components for the emd digital identity service
version: 1.1.3
homepage: null
environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.0
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0
  json_annotation: ^4.4.0
  provider: ^6.0.2
  result_dart: ^1.1.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.20
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
flutter: null
