name: "Pull request"
on:
  pull_request:
    branches:
      - main
jobs:
  validate_pr:
    permissions:
      pull-requests: write
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
      - name: Install dependencies
        run: flutter pub get && cd example && flutter pub get
      - name: Check licenses
        run: |
          dart pub global activate very_good_cli
          very_good packages check licenses

      - name: Run analyzer
        run: flutter analyze
      # Version
      - name: Install npm dependencies
        run: npm install
      # Run release cmd
      - name: Configure git
        run: |
          git fetch --prune --unshallow
          git config --global user.name "GitHub Actions"
          git config --global user.email "gh-actions@merckgroup.com"
      - name: Run release cmd
        run: npm run release
      - name: Get new version
        run: node echo_version.js >> $GITHUB_ENV
      - name: Push new version
        run: git push origin HEAD:${{ github.head_ref }}
      - name: Comment on PR with new version
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "# New version: ${{ env.VERSION }} 🚀 \n "
